export const EXPERIENCES_INFO = [
  {
    period: 'jun de 2023 - nov de 2023 · 6 meses',
    name:'Frontend Web e Mobile ',
    description:' ✓ Atuação na manutenção de código para solução de bugs e implementação de melhorias no sistema web e na aplicação mobile da empresa. ✓ Desenvolvimento em React/React Native com Typescript, e utilização do styled-components para estilização. ✓ Experiência com o recebimento de dados via WebSocket. ✓ Desenvolvimento do novo layout do sistema web utilizando Next 13 como biblioteca principal, e estilização com TailwindCSS. ✓ Versionamento de código utilizando Git, com hospedagem dos repositórios no GitHub. ✓ Participação em projetos seguindo a metodologia Scrum.',
    logoPath:'./logoExperience/spott.png',
    linkedin:'https://www.linkedin.com/company/evspott/',
    instagram:'https://www.instagram.com/spott.eco/',
    site:'https://spott.eco/',
   },
   {
    period: 'fev de 2023 - jul de 2023 · 6 meses',
    name:'Professor de tecnologia da informação',
    description: ' ✓ Lecionar em escola profissional de ensino médio e técnico conceitos de robótica, sistema operacional e hardware de computadores. ✓ Preparar os alunos para a carreira na área da tecnologia, fornecendo conhecimentos em desenvolvimento web. ✓ Auxiliar os alunos em projetos de software, incluindo trabalhos de conclusão de curso.',
    logoPath:'./logoExperience/gov-ceara.png',
    linkedin:'',
    instagram:'',
    site:'',
   },   
   {
    period: 'nov de 2021 - dez de 2022 · 1 ano 2 meses',
    name:'Frontend Web Developer PL',
    description: ' ✓ Prestar suporte a clientes, incluindo Fila, Humbro, Extrafarma, Promofarma, SaudeID e Orthocrin. ✓ Trabalhar em uma equipe dedicada a projetos de e-commerce. ✓ Realizar correções de bugs e levantamento de melhorias. ✓ Criar novos layouts conforme especificações da equipe de design. ✓ Atualizar versões e realizar testes em ambientes de homologação. ✓ Realizar o deploy da versão final. ✓ Utilizar tecnologias como Vtex IO, Vtex CMS, Vanilla JS, ReactJS, SASS, HTML, CSS e jQuery. ✓ Seguir o padrão de Web Design Responsive Mobile First. ✓ Trabalhar com disparo de eventos para o Google Analytics.',
    logoPath:'./logoExperience/codeby.avif',
    linkedin:'https://www.linkedin.com/company/codeby/',
    instagram:'https://www.instagram.com/grupocodeby/',
    site:'https://codeby.global/',
   },
   {
    period: 'jun de 2021 - jan de 2022 · 8 meses',
    name:'Frontend Web Developer',
    description: ' ✓ Desenvolver novas funcionalidades inovadoras para os clientes por meio da web. ✓ Objetivo de atender às necessidades e agregar valor ao dia a dia dos clientes. ✓ Implementar os princípios de UX para melhorar a experiência do usuário. ✓ Criar interfaces responsivas para dashboards, controle logístico e sistemas internos de gestão. ✓ Integração completa das funcionalidades desenvolvidas ao sistema próprio da empresa.',
    logoPath:'./logoExperience/infarma.png',
    linkedin:'https://www.linkedin.com/company/infarma-sistemas/',
    instagram:'https://www.instagram.com/infarmasistemas/',
    site:'https://www.infarma.com.br/',
   },
  {
   period: 'set de 2020 - mai de 2021 · 9 meses',
   name:'Frontend Web Developer JR',
   description: ' ✓ Contribuição na equipe de suporte e inovação para aplicativos, sites internos e projetos. ✓ Criação de telas intuitivas e precisas, conforme as solicitações recebidas. ✓ Foco na usabilidade para uma melhor integração com o usuário final. ✓ Desenvolvimento de telas para aplicativos de validação de dados, incluindo integração com APIs externas de segurança. ✓ Participação na equipe de briefing para levantamento de requisitos de novos projetos. ✓ Envolvimento na criação do frontend de dois projetos de imobiliária, incluindo a construção de um Dashboard e um Marketplace.',
   logoPath:'./logoExperience/mobs2.png',
   linkedin:'https://www.linkedin.com/company/mobs2/',
   instagram:'https://www.instagram.com/mobs2tech',
   site:'https://mobs2.com/',
  }   
]